version: '3.8'

services:
  csv-processor:
    image: csv-processor:latest
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes:
      - csv-processor-db:/prisma/dev.db
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=teste-mevo-@xpto
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  csv-processor-db: